[package]
name = "sr-queue-recovery"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
sr-common = { path = "../sr-common" }
