[package]
name = "sr-metrics"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
metrics-exporter-prometheus.workspace = true
tracing.workspace = true
